# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#
title: Pythia
logo: images/logo.png
logo_white: images/logo_white.png
email: info@pythiac.com
description: >- # this means to ignore newlines until "baseurl:"
  Open Source, Applied AI for All

#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: pythiac_com
github_username:  pythiac

repository: "pythiac/www"

projects:
  - HDI-Project/MLBlocks
  - HDI-Project/MLPrimitives
  - HDI-Project/BTB
  - HDI-Project/AutoBazaar
  - HDI-Project/SDV
  - HDI-Project/RDT
  - DAI-Lab/Copulas
  - DAI-Lab/CTGAN
  - DAI-Lab/TGAN
  - DAI-Lab/SDGym

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-octicons

# A list of the pages to display in the navigation bar
header_pages:
  - index.html
  - about.md

# Sections to display in the home page
home_sections:
  # - releases
  - about
  - columns
  - research
  - projects

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh

# gems:
#   - jekyll-octicons
